### ISSUE TITLE
gulp-jest-is-not-stopping-at-the-end-of-the-test-and-just-keep-looping-itself

### ISSUE THREAD

**Issue by ekanath25** [aarontrank/gulp-jest#55]

**Comment by gibbitz** [comment]
So my issue was that I was passing a file glob with multiple matches. Since I run Jest locally via CLI I was passing an empty config to the gulp module so both gulp and jest were looping my test files and jest was running for each glob match. 2 files -- two runs, 20 files -- 20 runs. Long story short:

do this:
```
return gulp.src('__test__').pipe(jest({}))
```
not 
```
return gulp.src('**.test.{js, jsx}').pipe(jest({}))
```
